name: linter and jest test
on: [push]
jobs:
  lint-jest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install
      - run: make install

